/*This (interface.c) file has been generated automatically by TinyDesigner. This file may get overwritten by TinyDesigner.DO NOT edit this file*/
#include <microwin/tnWidgets.h>
#include "interface.h"
#include "callback.h"

TN_WIDGET * create_window0(TN_WIDGET *parent)
{
TN_WIDGET *window0;
TN_WIDGET *menubar0;
TN_WIDGET *myfile;
TN_WIDGET *myopen;
TN_WIDGET *mysave;
TN_WIDGET *mysettings;
TN_WIDGET *myscreen;
TN_WIDGET *mycolor;

window0=tnCreateWidget(TN_WINDOW,parent,128,220,TN_WIDTH,551,TN_HEIGHT,424,TN_ENABLED,TN_TRUE,TN_VISIBLE,TN_TRUE,TN_CAPTION,"Window",TN_END);
tnAttachData(window0,strdup("window0"));
menubar0=tnCreateWidget(TN_MENUBAR,window0,3,16,TN_WIDTH,551,TN_HEIGHT,20,TN_ENABLED,TN_TRUE,TN_VISIBLE,TN_TRUE,TN_END);
tnAttachData(menubar0,strdup("menubar0"));
myfile=tnCreateWidget(TN_POPUPMENU,menubar0,TN_AUTO,TN_AUTO,TN_CAPTION,"File",TN_ENABLED,TN_TRUE,TN_EXCLUSIVE,TN_FALSE,TN_END);
myopen=tnCreateWidget(TN_MENUITEM,myfile,TN_AUTO,TN_AUTO,TN_CAPTION,"Open",TN_ENABLED,TN_TRUE,TN_CHECKABLE,TN_FALSE,TN_END);
mysave=tnCreateWidget(TN_MENUITEM,myfile,TN_AUTO,TN_AUTO,TN_CAPTION,"Save",TN_ENABLED,TN_TRUE,TN_CHECKABLE,TN_FALSE,TN_END);
mysettings=tnCreateWidget(TN_CASCADEMENU,myfile,TN_AUTO,TN_AUTO,TN_CAPTION,"Settings",TN_ENABLED,TN_TRUE,TN_EXCLUSIVE,TN_FALSE,TN_END);
myscreen=tnCreateWidget(TN_MENUITEM,mysettings,TN_AUTO,TN_AUTO,TN_CAPTION,"Screen",TN_ENABLED,TN_TRUE,TN_CHECKABLE,TN_FALSE,TN_END);
mycolor=tnCreateWidget(TN_MENUITEM,mysettings,TN_AUTO,TN_AUTO,TN_CAPTION,"Color",TN_ENABLED,TN_TRUE,TN_CHECKABLE,TN_FALSE,TN_END);
tnRegisterCallBack(myopen,CLICKED,opencall,NULL);
tnRegisterCallBack(mysave,CLICKED,savecall,NULL);
tnRegisterCallBack(myscreen,CLICKED,screencall,NULL);
tnRegisterCallBack(mycolor,CLICKED,colorcall,NULL);
return window0;
}

