#
# Copyright (C) Chris Johns (ccj@acm.org)
#
# Microwindows C++ Wrappers.
#

include $(CONFIG)

LIBNAME = libmwobjects.a
LIBNAMESO = libmwobjects.so

ifeq ($(OBJFRAMEWORK), Y)
CXXOBJS += mwobjects.o
endif

######################### Makefile.rules section #############################

include $(TOP)/Makefile.rules

######################## Tools targets section ###############################
