/*This (interface.c) file has been generated automatically by TinyDesigner. This file may get overwritten by TinyDesigner.DO NOT edit this file*/
#include<microwin/tnWidgets.h>
#include "interface.h"
#include "callback.h"

TN_WIDGET * create_window0(TN_WIDGET *parent)
{
TN_WIDGET *window0;
TN_WIDGET *button0;
TN_WIDGET *checkbutton0;

window0=tnCreateWidget(TN_WINDOW,parent,-188,-343,TN_WIDTH,300,TN_HEIGHT,200,TN_ENABLED,TN_TRUE,TN_VISIBLE,TN_TRUE,TN_CAPTION,"Window",TN_END);
tnAttachData(window0,strdup("window0"));
button0=tnCreateWidget(TN_BUTTON,window0,107,37,TN_WIDTH,60,TN_HEIGHT,30,TN_ENABLED,TN_TRUE,TN_VISIBLE,TN_TRUE,TN_CAPTION,"Button",TN_END);
tnAttachData(button0,strdup("button0"));
checkbutton0=tnCreateWidget(TN_CHECKBUTTON,window0,112,119,TN_WIDTH,83,TN_HEIGHT,13,TN_ENABLED,TN_TRUE,TN_VISIBLE,TN_TRUE,TN_CAPTION,"Check Button",TN_END);
tnAttachData(checkbutton0,strdup("checkbutton0"));
return window0;
}

